version: '3'
volumes:
  dados_dev:
networks:
  banco:
  microsserv:
services:
  db:
    build: docker_db
    # image: postgres:13.3
    # image: postgres:9.6
    #environment:
    #  - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      # volume dos dados
      - dados_dev:/var/lib/postgresql/data
      # script
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - banco
  micro:
    build: docker_micros
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - 50051:50051
    networks:
      - microsserv
      - banco
    depends_on:
      - db