version: '3'
volumes:
  dados_dev:
networks:
  banco:
  microsserv:
services:
  db:
    build: docker/docker_db
    # image: postgres:13.3
    # image: postgres:9.6
    #environment:
    #  - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      # volume dos dados
      - dados_dev:/var/lib/postgresql/data
      # script
      - ./docker/docker_db/scripts:/scripts
      - ./docker/docker_db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - banco
  micro:
    build: docker/docker_micros
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - 50051:50051
    networks:
      - microsserv
      - banco
    depends_on:
      - db
  jaeger:
    image: jaegertracing/all-in-one:1.29
    container_name: jaeger
    networks:
      - microsserv
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411